{% set name = "qdarkstyle" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QDarkStyle-{{ version }}.tar.gz
  sha256: 03d169ad6f3b96efa32568d941a3c3e0bbf5ae4041c3cd695a736d5f7477a439

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - qtpy >=1.9
    - helpdev >=0.6.10

test:
  imports:
    - qdarkstyle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/dev

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
