{% set name = "qdarkstyle" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QDarkStyle-{{ version }}.tar.gz
  sha256: d53b0120bddd9e3efba9801731e22ef86ed798bb5fc6a802f5f7bb32dedf0321

build:
  noarch: python
  number: 2
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - qtpy >=1.9

test:
  imports:
    - qdarkstyle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/dev

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
