{% set name = "qdarkstyle" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QDarkStyle-{{ version }}.tar.gz
  sha256: f55bd045c0c78e478ea5a2530f3739a2fcea8cbe038e4869ae450ae30feec3f7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - qtpy >=2.0

test:
  imports:
    - qdarkstyle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
