{% set name = "qdarkstyle" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/QDarkStyle-{{ version }}.tar.gz
  sha256: 0c0b7f74a6e92121008992b369bab60468157db1c02cd30d64a5e9a3b402f1ae

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy >=2.0

test:
  imports:
    - qdarkstyle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
