{% set name = "qdarkstyle" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QDarkStyle-{{ version }}.tar.gz
  sha256: 600584d625343e0ddd128de08393d3c35637786a49827f174d29aa7caa8279c1

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - qtpy >=1.9

test:
  imports:
    - qdarkstyle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
  license: MIT
  license_file: LICENSE.rst
  summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

  description: |
    Package that provides dark stylesheet for Qt applications
    (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).
  dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - goanpeca
